### ISSUE TITLE
Improvements on temp dir handling in case of cancellation or failure

### ISSUE THREAD

**Issue by aersamkull** [cyclosproject/ng-openapi-gen#100]
The temp dir could be improved for the case of cancellation of the generation process. If I cancel ng-openapi-gen there are some issues:

- The temp dir still contains files. If I did not "gitignore" the directory, I might accidently commit this. Therefore, please document the usage of the temp dir and allow to configure it's location
- As the temp dir contains files, the next generation will fail unless I delete the directory myself. Therefore, one could clean the generated directory before generating code

As always, I'd do a PR if you want.

**Comment by luisfpg** [comment]
Please, try this commit.
I've done several tests and for me the temp dir is always deleted now.
