### ISSUE TITLE
As a reportProgress asset in json or yaml ?. an example please

### ISSUE THREAD

**Issue by jairosolarte** [cyclosproject/ng-openapi-gen#103]
As a reportProgress asset in json or yaml ?. an example please
reportProgress ???
`/api/files:
    post:
      description: 
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary`

**Comment by luisfpg** [comment]
I think I din't understand your question fully, but it is not possible to use reportProgress with the generated methods. That is because the report progress makes the emitted value on the observable to be events instead of the expected type, and, thus, is not supported.
For example: ```service.method(): Observable<Result>``'. When reportProgress is used, the Observable would have an event emmitted, not the result.
