### ISSUE TITLE
The generators add and delete imports spaces after commit

### ISSUE THREAD

**Issue by ViieeS** [cyclosproject/ng-openapi-gen#106]
It's very strange behaviour, when I generate interfaces the generator adds spaces to generated services imports, than after commit it deletes it and then again and again...

![image](https://user-images.githubusercontent.com/8194543/82978762-03065180-9fee-11ea-80df-2af425dc8a46.png)

If I perform generation multiple times without any commits, all works fine.

I thought it's somehow related to WebStorm IDE, tried to disable this but nothing changed.

![image](https://user-images.githubusercontent.com/8194543/82979227-3695ab80-9fef-11ea-9f27-a0e435fd6594.png)

Also I tried to completely close IDE and use command line only.

**Comment by luisfpg** [comment]
The generated code always have a single space before / after brackets.
You probably have some other process reformatting the code.
Try with some blank Angular project, generate the classes and commit to a local repository - it will always have the 1 space.
