### ISSUE TITLE
Add suport for custom Handlerbars helpers

### ISSUE THREAD

**Issue by jmls** [cyclosproject/ng-openapi-gen#125]
I'd like to add a helper to the handlebars instance - is there a way of doing this so I can refer to the helper in a template ?

**Comment by eLarocque** [comment]
I am also in the same boat as jmls. Is there a hook somewhere that can be used to provide custom handlebar helpers? 
For example, we have HTML in the YAML descriptions that we would like to convert to Markdown when generating the TS code from the templates. Custom Handlebars support seems like an easy way to allow more customization options.

**Comment by luisfpg** [comment]
It is not currently possible.
We're open to help on this.

**Comment by eLarocque** [comment]
Hi, I have implemented the feature in a local branch. 
Requesting permission to push my branch for review :)
Thanks.

**Comment by luisfpg** [comment]
Sure, submit a pull request.

**Comment by eLarocque** [comment]
Sorry I'm fairly new to Github collaboration... Don't I need to be able to push to a new branch in order for a PR to be sent? I don't have permissions to push to this repo. Is it possible I need to be given access? Or is there another way to work in Github I'm not aware of ?

**Comment by eLarocque** [comment]
Nevermind I found out how using the forks. Sending PR shortly
