### ISSUE TITLE
is there a way to only generate interfaces?

### ISSUE THREAD

**Issue by rattkin** [cyclosproject/ng-openapi-gen#127]
is there a way to only generate interfaces?
I want to use generated interfaces also in node express app.
While there are other generators specifically for node, it could be nice to have the same file...

**Comment by rattkin** [comment]
ok sorry for bothering you, i'm gonna use https://www.npmjs.com/package/openapi-typescript-codegen it generates also services for node

**Comment by luisfpg** [comment]
There's no way to generate the models only.
You can, however, easily remove the services in your build script.
