### ISSUE TITLE
[Feature] Skip model generation

### ISSUE THREAD

**Issue by gideruette** [cyclosproject/ng-openapi-gen#132]
I'd like to skip model generation, to be able to generate on services (I generate model with another generator). 

Is it possible to add this option ?

Thanks

**Comment by luisfpg** [comment]
Sorry, it is not a generally useful solution.
The current time I have to invest in the project is minimal, so I won't add that option.
You can, however, use a script that wraps the call to ng-openapi-gen to some temporary folder, then copy only the services to your final directory and removing the temp dir.

**Comment by gideruette** [comment]
What if I make the PR ?

**Comment by luisfpg** [comment]
@gideruette of course, you're welcome to do the PR.
Still, I can't imagine this as a general solution.
The generated services import models from `../models/file.ts`.
Is your idea to just generate them in that folder, assuming the same name?
Also, what is the difference between the models generated by `ng-openapi-gen` and the ones by the other generator?
Another idea is to customize `ng-openapi-gen`'s templates to include the functionality you want.

**Comment by gideruette** [comment]
I understand that it's not the general use case. Y'ou're right, my idea is to generate models in the same file.
My generated models contains more precised information about model, that I use in Reactive Forms (input type, data domain, input label etc). It allows me to create stronger typed Reactive Forms, with better validation. 
Those information are not available in the swagger file, so I can't update templates to do that.
But your answer gave me an idea to bypass this constraint. If you're still interrested in the PR I can do it, it's ready.
Thank you for the answer !
