### ISSUE TITLE
endpoint returning content of type "application/octet-stream" not generated

### ISSUE THREAD

**Issue by KnutHaraldR** [cyclosproject/ng-openapi-gen#136]
No endpoint generated here, only if I choose something like "text/plain" instead.

"responses": {
            "200": {
              "description": "Success",
              "content": {
                "application/octet-stream": {
                  "schema": {
                    "type": "file",
                    "format": "binary"
                  }
                }
              }
            },

The problem with using "text/plain" is that it sets to 

      responseType: 'text',
      accept: 'text/plain'
      
   but I need:

        responseType: 'blob'

BTW: I had this working in SwaggerOpenApiGen for OpenAPI 2.

**Comment by luisfpg** [comment]
As per spec, `file` is not a valid type.
Try changing it to `string`.
