### ISSUE TITLE
allOf cause to type to be "any & any:

### ISSUE THREAD

**Issue by yantrab** [cyclosproject/ng-openapi-gen#138]
for example for this schema - 
```
              "schema": {
                "properties": {
                  "password": { "type": "string", "minLength": 6 },
                  "email": { "format": "email", "type": "string", "allOf": [{ "transform": ["trim"] }, { "minLength": 1 }] }
                },
                "type": "object",
                "required": ["password", "email"]
              }
```

the result is - 

`login$Response(params: { password: string; email: any & any }): Observable<StrictHttpResponse<User>> {}`

(i using it to forbidden empty string, i using ajv in client side also  - https://stackoverflow.com/questions/45888524/empty-values-validation-in-json-schema-using-ajv)

**Comment by luisfpg** [comment]
Sorry, but the support on generator is limited to valid OpenAPI descriptors.
This is out of scope.
