### ISSUE TITLE
My parameters are not working correctly

### ISSUE THREAD

**Issue by ezequielobreque** [cyclosproject/ng-openapi-gen#141]
Hi.
I am new to using this module, but I have a problem the get parameters do not work correctly.
thanks for your time
![Captura de pantalla (22)](https://user-images.githubusercontent.com/18178043/106282502-6ef52580-621f-11eb-9d89-0d6382e8a051.png)

![Captura de pantalla ((23)](https://user-images.githubusercontent.com/18178043/106282769-d27f5300-621f-11eb-9a83-c99bf2098408.png))

![Captura de pantalla (25)](https://user-images.githubusercontent.com/18178043/106282934-08243c00-6220-11eb-9197-51d8c5596f9d.png)

**Comment by luisfpg** [comment]
Sorry, would need more info for helping.
You've just posted a bunch of screenshots.
Describe in more details what doesn't work, and post your openapi descriptor

**Comment by ezequielobreque** [comment]
Don't worry about the problem, the answer to problem 112 solved my problems.
The error is that you don't have Array.From(this._query.values ​​()) the For.
Gracias Por su tiempo!!!
