### ISSUE TITLE
Not all models are generated when modelPrefix is given

### ISSUE THREAD

**Issue by rajgopalv** [cyclosproject/ng-openapi-gen#15]
Hi @luisfpg Thanks for the patch for #13 . But, i'm afraid this did not fully fix the issue. It generates certain models and ignores some of them. To reproduce please try this..

Download https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml and store it as petstore.yaml
`run ng-openapi-gen -i petstore.yaml -o petstoreClient`
Please Note: in the petstoreClient/models you will see 3 models. Good! This is the expected behaviour.

But....
Now to repro the error, use the following conf file
```
$ cat conf.json 

{
    "module": "MyPetStore",
    "configuration": "MyPetStoreClientConfiguration",
    "servicePrefix": "MyPetStore",
    "serviceIndex": "my-pet-store",
    "modelIndex": "my-pet-store-models",
    "modelPrefix" : "TestPrefix"
}
```
now try `ng-openapi-gen -i petstore.yaml -o petstoreClientWithPrefix -c conf.json`
you will see only 1 file in petstoreClient/models

**Comment by luisfpg** [comment]
Thanks for the report. Will take a look on it this week.

**Comment by rajgopalv** [comment]
Thanks..

more info : the bug seems to be in `ignoreUnusedModels`. I'm getting around the problem by setting "ignoreUnusedModels" : false.

**Comment by JustinM16** [comment]
Hi,
I am getting this error too but instead I am getting no models generated.
My Config File is:

{
  "$schema": "https://raw.githubusercontent.com/cyclosproject/ng-openapi-gen/master/ng-openapi-gen-schema.json",
  "input": "http://localhost:8080/v2/api-docs",
  "output": "src/app/api",
  "ignoreUnusedModels": false
}

The Command Im using is:
ng-openapi-gen -c ng-openapi-gen.json

and the result is:
Generation from http://localhost:8080/v2/api-docs finished with 0 models and 2 services.
