### ISSUE TITLE
Question: Why is there no "minParamsForContainer" option like with ng-swagger-gen?

### ISSUE THREAD

**Issue by Diedinium** [cyclosproject/ng-openapi-gen#150]
Hi there,

I'm currently migrating one of our organisations projects from a Swagger 2.0/OpenApi 2 specification (and therefore the `ng-swagger-gen` library), to this one.

It seems to work in a very similar way, which I'm thankful for, however it's making my life difficult that `ng-openapi-gen` does not have the `minParamsForContainer` config option.

This is going to result in me needing to go through and refactor our entire codebase to pass through objects for simple get methods that are only expecting an Id.

As an example, here is what the generated service method looks like currently:

```javascript
this.organisationService.organisationGet(someIdVarHere) 
```

Which will now need to look like this instead:

```javascript
this.organisationService.organisationGet({ id: someIdVarHere })
```

So, before I go ahead and have to change this in a couple hundred locations as part of the refactor, I have two questions:

1. Is there any equivalent to the "minParamsForContainer" in this library?
2. If not, I'm assuming it was not implemented for a reason, can someone explain the decision/reasoning there?
    - If it's not implemented out of an intentional decision; can "minParamsForContainer" be implemented as a config option?

**Comment by luisfpg** [comment]
It was not implemented from the very beginning.
This made the implementation easier.
There are no plans to add it, unless a PR is contributed.
In that case, it should be implemented as a configuration option, with 0 as default value to keep the backwards compatibility.

**Comment by Diedinium** [comment]
@luisfpg Thank you for the reply, and fair enough, I'll live with it then as I don't have the time to try and contribute something like that at the moment.
