### ISSUE TITLE
Inline objects don't honor "nullable": true

### ISSUE THREAD

**Issue by Fabiencdp** [cyclosproject/ng-openapi-gen#151]
Hi ! 

First, thanks for this awesome work! Generated api are time saving! 

I just noticed that "nullable: true" is not generated as it should be. Did i miss something ? 

Here is an example : 

Schema part with a number property that can be null : 

```
      "requestBody": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "required": ["someId"],
              "properties": {
                "someId": {
                  "type": "number",
                  "nullable": true
                }
              }
            }
          }
        }
      }
 ```

Here is what the module generate (simplified): 
```
  methodName(params: {
    body: { 'someId': number }
  }): Observable<{ ... some response stuff ... }> }> {

    return this.methodName$Response(params).pipe(
      map((r: StrictHttpResponse<{ ... some response stuff ...  }> })
    );
  }
```

I would except ``` body: { 'someId': number | null }```

If found the same behaviors with the return parameters of every methods.
On the other hand, generated models are typed correctly. 

Is that a normal ?

**Comment by luisfpg** [comment]
This seems to be a bug with inline models
