### ISSUE TITLE
Automatically omit operationId prefix if it is the same as the controller name *feature request*

### ISSUE THREAD

**Issue by begrs** [cyclosproject/ng-openapi-gen#169]
A usual convention for operationIds in OpenApi3 is to use either ControllerName_HttpMethod or ControllerName_ActionName.
In the generated services this produces typescript code like this:
ControllerService.ControllerNameActionName
or with a concrete example:
for action names: UserService.userSave
and for http method names: UserService.userPost

If the controller name matches the start of the method, it is more readable to omit the prefix
(The prefix is necessary at all because operationsIds have to be unique per application)
like this:
UserService.save or UserService.post

Since chaning this as default would break existing generation setups, hiding it behind a new option would be a nice feature.

**Comment by begrs** [comment]
As far as I understand the LoopBack documentation, its designed for nodejs backend and I could not find any example of how to add x-operation-name as a custom attribute to an asp.net (.net core 3.1) backend.

Do you have any further documentation or examples that could help me?

**Comment by luisfpg** [comment]
Sorry, I don't have any contact with .net....
Doesn't it support a way to specify a vendor extension?
