### ISSUE TITLE
Feature: Define baseurl / path in config file for base-service.ts

### ISSUE THREAD

**Issue by biijoy508** [cyclosproject/ng-openapi-gen#171]
Want to be able to set base-service.ts rooturl from ng-openapi-gen.json file or in generate command

**Comment by luisfpg** [comment]
The supported methods are the ones described here: https://github.com/cyclosproject/ng-openapi-gen#specifying-the-root-url--web-service-endpoint

**Comment by SharmaHarsh7** [comment]
Does that means we will have to configure it in every component earlier I used to do that in app.config.is in standalone applications:

`export const appConfig: ApplicationConfig = {
    providers: [
        provideRouter(appRoutes, withInMemoryScrolling({ anchorScrolling: 'enabled', scrollPositionRestoration: 'enabled' }), withEnabledBlockingInitialNavigation()),
        provideHttpClient(
            withFetch(),
            withInterceptors([authInterceptor])
        ),
        provideAnimationsAsync(),
        providePrimeNG({ ripple: true,theme: { preset: Aura, options: { darkModeSelector: '.app-dark' } } }),
        importProvidersFrom(ApiModule.forRoot({ rootUrl: environment.api_host })),
        MessageService,
        ConfirmationService,
        EnvironmentConfig,
        ConfigService,
        ValidationService,
        NavService,
        UserInfoService,
        DSFormBuilder,
        DialogService,
        { provide: LocationStrategy, useClass: PathLocationStrategy },
        { provide: TokenAuthService, useFactory: initAuthService, deps: [HttpBackend, UserInfoService, ApiConfiguration] },
        { provide: ModelMetaDataService, useFactory: initModelMetaData, deps: [HttpClient, ConfigService, EnvironmentConfig] }
    ]
};`

is there an easy alternative of this as I want to setup this up as very first thing  when the app is loading asn app will start making call in auth guards and every other where.
