### ISSUE TITLE
Generation of models from swagger 2.0 not working

### ISSUE THREAD

**Issue by benjamindamm** [cyclosproject/ng-openapi-gen#185]
Hi I am using ng-openapi-gen. It works fine for generating all the services. But it seems to ignore all models which are referenced in my openApi file. The generation process ends with "Generation from ./openapi.json finished with 0 models and 5 services." The generated services are referencing directories such as "../models/" but the file itself for the model wasn't created.

I tried the option "ignoreUnusedModels": false with absolute no effect. Is anybody else facing this issue? I know that this mechanism worked well in the past for the whole project. I am not sure what has changed.

Another issue is, that I cant use URLs anymore to reference files. I had to copy the content into a local .json file. From my perspective its a huge issue that you cant really know what the tool is doing. It prints just the result of 0 models and 5 services. Not why anything has been skipped. Or more important for this case, why its not possible to read a file from an url. 

Here is an example of my open-api file:

```json
{
  "swagger": "2.0",
  "info": {
    "description": "Api Documentation",
    "version": "1.0",
    "title": "Api Documentation",
    "termsOfService": "urn:tos",
    "contact": {},
    "license": { "name": "Apache 2.0", "url": "http://www.apache.org/licenses/LICENSE-2.0" }
  },
  "host": "localhost:9080",
  "basePath": "/",
  "paths": {
    "/api/mappings": {
      "get": {
        "tags": ["admin-resource"],
        "summary": "",
        "operationId": "",
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": { "type": "array", "items": { "$ref": "#/definitions/ApplicationDTO" } }
          },
          "400": { "description": "Description" },
          "401": { "description": "Unauthorized" },
          "403": { "description": "Forbidden" },
          "404": { "description": "Not Found" }
        }
      }
    }
  },
  "definitions": {
    "ApplicationDTO": {
      "type": "object",
      "properties": {
        "applicationId": { "type": "string" },
        "applicationName": { "type": "string" },
        "roleMappings": { "type": "array", "items": { "$ref": "#/definitions/DTOMapping" } }
      },
      "title": "ApplicationDTO"
    },
    "DTOMapping": {
      "type": "object",
      "properties": {
        "logicRoleName": { "type": "string" },
        "roleNames": { "type": "array", "items": { "type": "string" } }
      },
      "title": "DTOMapping"
    }
  }
}

```

UPDATE: I converted this config from V2 of swagger to OpenAPI V3 and it worked. You should support V2 too, or you could output something on the console.

**Comment by luisfpg** [comment]
See https://github.com/cyclosproject/ng-openapi-gen#readme
For Swagger 2.0, use https://github.com/cyclosproject/ng-swagger-gen (which is largely unmaintained at this time)
