### ISSUE TITLE
upgrade json schema from ^0.3.0 to 0.4.0

### ISSUE THREAD

**Issue by thomasbricchi** [cyclosproject/ng-openapi-gen#186]
I got his using npm audit fix --force

json-schema  <0.4.0
Severity: moderate
json-schema is vulnerable to Prototype Pollution - https://github.com/advisories/GHSA-896r-f27r-55mw
No fix available
node_modules/json-schema
  ng-openapi-gen  *
  Depends on vulnerable versions of json-schema
  node_modules/ng-openapi-gen

2 moderate severity vulnerabilities

resoursces: 
- https://sca.analysiscenter.veracode.com/vulnerability-database/security/prototype-pollution/javascript/sid-32973
- https://github.com/advisories/GHSA-896r-f27r-55mw

**Comment by luisfpg** [comment]
It was already updated to 0.4.0 in 0.20.0
