### ISSUE TITLE
typescript noImplicitOverride: true results in error in the generated code

### ISSUE THREAD

**Issue by ondrakoupil** [cyclosproject/ng-openapi-gen#187]
Typescript 4.3 introduces an "override" keyword and noImplicitOverride option in tsconfig.json.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#override-and-the---noimplicitoverride-flag

When "noImplicitOverride" is set to true (which is default in Angular 13), then the code generated by ng-openapi-gen is broken. Typescript then requires explicitly marking all overridings of a base method by "override" keyword, and generated file "request-builder.ts" contains a class PathParameter extending Parameter and its method serializeValue, but it lacks the override keyword, leading to a compile error.

Safest way would be just to add the "override" word to that method in the template for generating request-builder.ts. However I understand that this would break the code for those using TS < 4.3. Maybe a new configuration option would do, something like "target" in typescript, that would enable users to mark the level of typescript code they want to have generated?

**Comment by rjalexander** [comment]
I am also facing the same issue. Maybe the simplest solution would be just adding a ts-ignore to that line? That way it would compile for both "noImplicitOverride" and older versions without needing a "target".

**Comment by luisfpg** [comment]
Thanks @rjalexander for the tip with `@ts-ignore`.
This is released with 0.19.4.
