### ISSUE TITLE
Allow running without a configuration file, and add mnemonics -i / -o for --input / --output

### ISSUE THREAD

**Issue by gilsdav** [cyclosproject/ng-openapi-gen#2]
Hello, is it possible to have same CLI options as `ng-swagger-gen` ?
I want to use same config only by switching the library.

I want to use it like this : `ng-openapi-gen --gen-confi -i https://gist.githubusercontent.com/kinlane/43934f44fd591a6ee59a45267d9e3066/raw/47f6d7115dd17749c408c55861638ffc22d995f4/sample-openapi-30.yaml -o ./src/api -c ng-swagger-gen-api.json`

Thank's in advance.

**Comment by luisfpg** [comment]
The command-line arguments in come directly from the options JSON schema.
I could, however, add a mapping for some shorter mnemonics for the input and output options, would be handy.
