### ISSUE TITLE
Does interface extends OR union type work in 0.20.0

### ISSUE THREAD

**Issue by malvin-metamatics** [cyclosproject/ng-openapi-gen#202]
Hello together, having an allOf in the input schema:
```json
"SpecificDTO": {
    "type": "object",
    "allOf": [
        {
            "$ref": "#/components/schemas/AbstractDTO"
        }
    ]
},
```
I expect the result to be:
```ts
interface SpecificDTO extends AbstractDTO
```
or a similar solution using union types (having read a couple of issues and PRs here).

For me it seems I can not do that. Can you tell me if it is possible or not?

Thanks a lot in advance!

**Comment by malvin-metamatics** [comment]
I found the reason for it. When I use the following definition:
```json
"SpecificDTO": {
    "type": "object",
    "allOf": [
        {
            "$ref": "#/components/schemas/AbstractDTO"
        }
    ]
},
```

it does NOT work because of the `"type": "object"`

When I remove the type it works as expected. But I see not why it changes the behavior. Any ideas?

**Comment by luisfpg** [comment]
It is an invalid definition to have both type:object and allOf.
The generator could either break or decide which one to follow.
