### ISSUE TITLE
Generating of a client as Angular library

### ISSUE THREAD

**Issue by ISTAnsver** [cyclosproject/ng-openapi-gen#207]
Hello!

It is going to be cool if _ng-openapi-gen_ will have ability to generate an API client as Angular library that exporting an api module, services and models through _public-api.ts_.
For providers(backend developres) this feature gives ability to supply the API client to customers(frontend developers) out of the box. Providers can use _ng-openapi-gen_ tool in CI/CD process and generate the API client within a pipeline that used for the API. When API updates then the API client updates too.
For consumers this feature makes an integration easier. They must just install/update a package and don't worry anything else.All problems with integration in such case can be solved through `npm i`.
It can increase software development speed in teams.

It sounds good enough)

**Comment by luisfpg** [comment]
As far as I understand, all pieces are there. To generate a library, all you need is a library project, with the correct pieces in place. ng-openapi-gen generates a module already.
However, generating a whole project is out of scope.

**Comment by ISTAnsver** [comment]
Got it!
Thank you for the answer!

**Comment by ashblue** [comment]
I would also love to have a public api file auto generated. Our team is using this library to generate code in a monorepo right now as an Angular library.
