### ISSUE TITLE
Question: How to get rid of  `Operation '/api/Documents.get' didn't specify an 'operationId'. Assuming 'apiDocumentsGet'.`

### ISSUE THREAD

**Issue by Lonli-Lokli** [cyclosproject/ng-openapi-gen#221]
I am getting a lot of such messages with code generation, how can I avoid them with Swashbuckle 
```

Operation '/api/Documents.get' didn't specify an 'operationId'. Assuming 'apiDocumentsGet'.
Operation '/api/Documents.put' didn't specify an 'operationId'. Assuming 'apiDocumentsPut'.
```

**Comment by TheRealGI** [comment]
Hey @Lonli-Lokli 
 It's hard to tell without a spec but according to this warning there is no [operationId ](https://swagger.io/docs/specification/paths-and-operations/#:~:text=role%3Dvalue-,operationId,-operationId%20is%20an)set.  If you want to set a custom operationId preventing the package from generating one for you simply add the `Name` property to the HTTP action filter. For example 
`[HttpGet(Name="GetDocuments")]`

**Comment by Toxantron** [comment]
We use this in our `StartUp.cs`. It generates methods with the same name as the server side methods

````cs
services.AddSwaggerGen(c =>
{
  c.CustomOperationIds(api => ((ControllerActionDescriptor)api.ActionDescriptor).MethodInfo.Name);
});
````

**Comment by Lonli-Lokli** [comment]
Thanks, I am using now this within class SwaggerDefaultValues : IOperationFilter

```
operation.OperationId ??= string.Join(string.Empty, (new string[] { apiDescription.HttpMethod ?? string.Empty })
            .Concat((apiDescription.RelativePath ?? string.Empty).Split(@"/"))
            .Select(word => string.Join(string.Empty, word.Split('{', '}')))
            .Select(FirstCharToUpper));
```
