### ISSUE TITLE
since version 19.0 RequestBuilder is not named after config

### ISSUE THREAD

**Issue by dvag-desiree-sybertz** [cyclosproject/ng-openapi-gen#224]
In version 19.0 there was a change in templates/requestBuilder.handlebars 

![Bildschirmfoto 2022-05-24 um 09 37 58](https://user-images.githubusercontent.com/62477296/169975689-a8f22700-2a0a-4703-9d49-ade7c82f3273.png)

I think because of this change, RequestBuilder will no longer be named after config. In the imports, the RequestBuilder is still named after the config, which is why the generated code has errors.

**Comment by tracerco-peter** [comment]
We have just noticed this issue today.

Look's like this merge changed the handlebars template.

https://github.com/cyclosproject/ng-openapi-gen/commit/4abbac20957670e4c8fff814d68a27a8779255ec#diff-48727b1ae18c87e8fcf1209c58c490496f4be3e979cb38aa054cc9ef78b19d24L199
