### ISSUE TITLE
OneOf (from official doc) not working

### ISSUE THREAD

**Issue by dgilsonAfelio** [cyclosproject/ng-openapi-gen#233]
Using this example: https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

Using the latest version of ng-openapi-gen.

![image](https://user-images.githubusercontent.com/64957020/183611533-c0380fe3-fd77-45b1-b133-f0d6943f4241.png)

![image](https://user-images.githubusercontent.com/64957020/183611663-3ddfcdbe-1ed9-48d0-a537-6494bbe6f1d1.png)

What I got: 
![image](https://user-images.githubusercontent.com/64957020/183611847-6f34758a-3877-4385-be46-ba751dc2e90e.png)

What I expect:
![image](https://user-images.githubusercontent.com/64957020/183612125-a40999b9-aeca-49cd-8953-8bf066c1f730.png)

**Comment by dgilsonAfelio** [comment]
It works if I add this into `model.js`:
![image](https://user-images.githubusercontent.com/64957020/183644027-c9aa237f-3613-41cb-90c7-93951ca3fe13.png)

And this into `gen-util.js`:
![image](https://user-images.githubusercontent.com/64957020/183644203-3acd3f7b-f9a9-463c-b684-5a5923278c3f.png)
![image](https://user-images.githubusercontent.com/64957020/183644260-1fd4183c-b07a-45f2-8875-6ed44a2baa24.png)

**Comment by dgilsonAfelio** [comment]
Workaround:
Utiliser le oneOf seul dans un objet et utiliser un allOf pour hériter de cet objet.
![image](https://user-images.githubusercontent.com/64957020/183648293-fa55f155-4d78-421e-a0f4-b743916df703.png)

**Comment by BrothersWar** [comment]
Same problem. I simply add hasOneOf to `model.js` as in example above 
```
const hasOneOf = schema.oneOf && schema.oneOf.length > 0;
this.isObject = (type === 'object' || !!schema.properties) && !schema.nullable && !hasAllOf  && !hasOneOf;
```

@luisfpg could please fix this next release
