### ISSUE TITLE
[HELP] How do you use the ApiRequestConfiguration

### ISSUE THREAD

**Issue by liamkavfc** [cyclosproject/ng-openapi-gen#236]
I have implemented the ApiRequestConfiguration class in my app, but I am unsure how to actually use it.

I understand that you set the headers before the intercept, but then the apply method takes a HTTPRequest, how do I get this out of my generated service methods?

**Comment by luisfpg** [comment]
I'm sorry for the late reply, but it is explained in the [README](https://github.com/cyclosproject/ng-openapi-gen/#passing-request-headers--customizing-the-request)
