### ISSUE TITLE
If-None-Match header not being set properly

### ISSUE THREAD

**Issue by stsomewheredesign** [cyclosproject/ng-openapi-gen#241]
The API that we're running ng-openapi-gen against supports both the `If-Match` and `If-None-Match` headers to handle concurrency issues. This is on a call-by-call basis so it is not feasible to create an HTTP Interceptor to add it to every request. But, as it stands, these headers do not appear to be implemented as expected.

The service generator picks up from Swagger that the headers could be present for a specific call, but when the call is actually made, there is an unreported error being displayed in Chromium DevTools which prevents the call from continuing.

Here is an example of a call setting the `If-None-Match` header:
![image](https://user-images.githubusercontent.com/22261480/195086137-4e4402c3-7c8d-4637-bcea-b03911bd9696.png)

When attempting this call through the Swagger UI, the header shows up in curl as a value completely enclosed as a string value:
![image](https://user-images.githubusercontent.com/22261480/195092715-56d487a8-a443-455b-b3fa-5b6cf082bb8c.png)

It does not show as an enclosed string value via DevTools, but as the images show below, there is something in how that header is being set that's preventing the call from being processed.

The first image is with the header set to the same value as was set in Swagger, the second image doesn't not contain the header at all. As you can see, the first call never gets processed, the second call does, but with the expected error received due to not having the `If-None-Match` header set.
![image](https://user-images.githubusercontent.com/22261480/195091111-cb899c34-7bf3-48d7-858a-3d3976c70b3d.png)

![image](https://user-images.githubusercontent.com/22261480/195091219-9806de04-1eab-404f-b44a-d09de90447f8.png)

I would appreciate a review of this issue and an update as this is preventing progress from continuing on a vital project.

**Comment by luisfpg** [comment]
I'm sorry, but I don't understand exactly the problem.
![image](https://user-images.githubusercontent.com/1183737/196167672-d88ba800-8d5b-476f-8a82-bd12a6df3adb.png)
We can see in the image that the header is being sent....
The fact that the CURL command shows it between quotes is just a representation.

What is the error exactly? Please, attach the error trace of both client and server.

**Comment by luisfpg** [comment]
Closed due to inactivity.
In case the problem persists, please, comment again and I'll reopen it.
