### ISSUE TITLE
Unexpected end of json input

### ISSUE THREAD

**Issue by Panix123** [cyclosproject/ng-openapi-gen#251]
As of lately I am facing the issue that the API I am trying to generate from my python fastapi  return thhe following error:

Error on Api generation: SyntaxError: Unexpected end of JSON input

The JSON is valid, I have confirmed that via some tools. Also tried copying the JSON into a file and generating it from there, but sadly I get the same result... is this a known issue?

Versions used:
ng-openapi-gen: 0.21.2
Angular: 14.1.1
Fastapi: 0.79.0

I have not updated anything since the last time I generated the API

**Comment by Panix123** [comment]
Okay, I found the problem, but am not 100% sure why that is.

Just make a config file instead of giving input and output as parameters, because somehow the code thinks that a "ng-openapi-gen.json" exists (in the node_modules folder which is not the case by default.

If you then make a file in your project folder (apiconfig.json) and jsut make the call "ng-openapi-gen -c ./apiconfig.json", you overwrite the default file the code is searching for.

**Comment by luisfpg** [comment]
Ok, closing it for now.
