### ISSUE TITLE
Nullable array elements are not generated nullable in models

### ISSUE THREAD

**Issue by flpa** [cyclosproject/ng-openapi-gen#255]
Hey, 
I'm currently working on an API with the following type:
```json
{
  "TfcHeaderFilterDTO": {
    "required": [
      "values"
    ],
    "type": "object",
    "properties": {
      "typeExclude": {
        "type": "boolean"
      },
      "values": {
        "type": "array",
        "items": {
          "type": "string",
          "nullable": true
        }
      }
    }
  }
}
```

The "values" property is supposed to hold an array of nullable Strings.
According to this topic, the items should be explicitly marked as nullable in such cases (like in my snippet above):
https://community.smartbear.com/t5/Swagger-Open-Source-Tools/Array-null-values/td-p/192153

However, when generating models for the API, the type is generated as follows:
```typescript
export interface TfcHeaderFilterDto {
  typeExclude?: boolean;
  values: Array<string>;
}
```

What I am trying to achieve is something like this, though:
```typescript
export interface TfcHeaderFilterDto {
  typeExclude?: boolean;
  values: Array<string | null>;
}
```

Am I missing something? Or is there a way to make ng-openapi-gen generate the type like that?

**Comment by luisfpg** [comment]
This seems like a bug.
Unfortunately I'm having little to no time for this project.
But I'll try to include it in the next release.
