### ISSUE TITLE
enumStyle option has no effect

### ISSUE THREAD

**Issue by gwesterman** [cyclosproject/ng-openapi-gen#273]
Using v0.24.1, no matter what value for enumStyle I use ("alias", "upper", "pascal", "ignorecase") the following schema:

```json
"status":{
   "type":"string",
   "enum":[
      "ACTIVE",
      "INACTIVE",
      "SUSPENDED",
      "BANNED",
      "DELETED"
   ]
}
```

always results in the following generated output:

```javascript
status?: 'ACTIVE' | 'INACTIVE' | 'SUSPENDED' | 'BANNED' | 'DELETED';
```

Note: It also does not default to "pascal" but to "upper".

I'd also much rather prefer an actual enum to be generated which I can then use in my code.

**Comment by luisfpg** [comment]
The enumStyle option is only used for models defined as enums, not for nested property declarations, which are always declared as an inline type.
this has been proposed before, but is out of scope, because it would require the model to export additional enums, which complicates generation.
