### ISSUE TITLE
[Bug]: ApiService malformed types

### ISSUE THREAD

**Issue by Roman991** [cyclosproject/ng-openapi-gen#288]
https://github.com/cyclosproject/ng-openapi-gen/blob/master/templates/apiService.handlebars
` 46 invoke<P, R>(fn: ApiFnRequired<P, R> | ApiFnOptional<P, R>, params?: P, context?: HttpContext): Observable<R></R>   {`
Can you check dat `</R>` at line 46.

After removing it, the ide still complains about
![image](https://github.com/cyclosproject/ng-openapi-gen/assets/10634244/07d5e0f2-cf5d-4086-8e63-e2292f7fa936)

In my case I set every `params` to `params: P` (not optional) and it worked.

**Comment by luisfpg** [comment]
The point is that some operations can have optional parameters, while others, required parameters.
We have several operation with both optional and required parameters and we don't see errors in the IDE.
Can you post the operation definition (yaml or json)?
