### ISSUE TITLE
Generate models only flag / generate model of paths with certain tag

### ISSUE THREAD

**Issue by LendaVadym** [cyclosproject/ng-openapi-gen#289]
Is it possible to add support for the following features:
1) possibility to generate models only. It could be a flag in a configuration file.
2) possibility to generate only models related to paths (endpoints) that were filtered by "includeTags" or "excludeTags" options. Currently, event if I filter paths (endpoints) by tag, all models are generated.

**Comment by luisfpg** [comment]
It is not possible.
Starting with 0.50.x, a function is generated per operation variant.
You can, however, disable services generation by setting `"services": false` in options.
You'll have a bunch of functions which, when not referenced, won't be included in the output by Angular, so don't have any impact in the application.
