### ISSUE TITLE
All properties of simpletype is set to optional

### ISSUE THREAD

**Issue by eirikmars** [cyclosproject/ng-openapi-gen#290]
I've encountered an issue where the properties of simpletype are being marked as optional, despite being specified as required in the OpenAPI 3.0.1 documentation. This happens to all child properties.

**OpenAPI Configuration:**
```
***
"openapi": "3.0.1",
***
"PensionDto": {
  "required": [
    "hasDisabilityPension",
    "productName",
    "productType"
  ],
  "type": "object",
  "allOf": [
    {
      "$ref": "#/components/schemas/ProductDto"
    },
    {
      "type": "object",
      "properties": {
        "hasDisabilityPension": {
          "type": "boolean"
        }
      }
    }
  ]
}
```
**Generated TypeScript Code:**
`
export type PensionDto = ProductDto & {
'hasDisabilityPension'?: boolean;
};`

Here "hasDisabilityPension" is present in the "required" field in the openApi 3.0.1 docs, but is still set to optional in the generated code. Is there a handlebar file or any CLI arguments where I can change this behaviour?

**Comment by luisfpg** [comment]
A type can't be of both types 'object' and 'allOf' at the same time.
Try this:

```json
"PensionDto": {
  "allOf": [
    {
      "$ref": "#/components/schemas/ProductDto"
    },
    {
      "type": "object",
      "required": [
        "hasDisabilityPension"
      ],
      "properties": {
        "hasDisabilityPension": {
          "type": "boolean"
        }
      }
    }
  ]
}
```
