### ISSUE TITLE
Wrong import path for model files in index.ts

### ISSUE THREAD

**Issue by scurk1415** [cyclosproject/ng-openapi-gen#291]
Not sure if i am doing something wrong or if there is a bug with the import paths for model files if you are using the `"indexFile": true` config. All model import paths are missing the `./models` prefix. So if i have a User model then the generated code is 

```
export { User } from '/api-sport';
```

instead of 
```
export { User } from './models/api-sport';
```

It works ok for services.

I am using the lates 0.50.2 version of this library. The generation also works ok with the 0.25.1 version, so i guess something is wrong with the 0.50.x version of the library

**Comment by scurk1415** [comment]
Here is the reproduction: https://github.com/scurk1415/open-api-reproduction

Just run `npm run generate-api` and then check src/app/api/index.ts

The line `export { Test } from '/test';` has errors

**Comment by luisfpg** [comment]
Is it the same result with the latest 0.50.3?

Em ter., 10 de out. de 2023 11:09, GLaw ***@***.***> escreveu:

**Comment by scurk1415** [comment]
My reproduction repository above has v0.50.3 and the errors still persist

**Comment by mokeev1995** [comment]
@luisfpg can confirm that this bug still exists.

here's example swagger.json with the same issue

<img width="641" alt="Снимок экрана 2023-10-15 в 02 50 52" src="https://github.com/cyclosproject/ng-openapi-gen/assets/8450876/f3831e38-028e-43fa-9214-25b492133b98">

[swagger.json](https://github.com/cyclosproject/ng-openapi-gen/files/12908245/swagger.json)

**Comment by mokeev1995** [comment]
@luisfpg if i understand correctly, the bug is here:

https://github.com/cyclosproject/ng-openapi-gen/blob/master/templates/index.handlebars#L6

Possibly this
```
{{#modelIndex.imports}}export { {{{typeName}}}{{#useAlias}} as {{{qualifiedName}}}{{/useAlias}} } from '{{{file}}}';
{{/modelIndex.imports}}
``` 

Should be this

```
{{#modelIndex.imports}}export { {{{typeName}}}{{#useAlias}} as {{{qualifiedName}}}{{/useAlias}} } from './models/{{{file}}}';
{{/modelIndex.imports}}
```
