### ISSUE TITLE
Query parameters do not recognize "nullable": true if "required" is true

### ISSUE THREAD

**Issue by Timkoeln** [cyclosproject/ng-openapi-gen#293]
Hello, thank you for the great work!

I just noticed that "nullable: true" is not generated as it should be when "required" is true. Did I miss something?

Here an example API:

```
openapi: 3.0.1
info:
  title: Test
  version: "1.0"
servers:
  - url: https://localhost/api
paths:
  /test:
    get:
      tags:
        - ExampleGet
      summary: ExampleGet
      operationId: ExampleGet
      parameters:
        - name: filter
          in: query
          required: true
          style: form
          schema:
            type: integer
            nullable: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
```

Here is what the module generate:
```
  exampleGet(params: {
    filter: number;
  },
  context?: HttpContext

): Observable<Array<string>> {

    return this.exampleGet$Response(params,context).pipe(
      map((r: StrictHttpResponse<Array<string>>) => r.body as Array<string>)
    );
  }
```
I would except:
```
  exampleGet(params: {
    filter: number | null;
  },
```
Is the behavior correct ?

**Comment by Timkoeln** [comment]
Hey!
Thanks for the quick fix! I noticed that null query params are filtered out in the request builder. Is this expected? I would expect if you explicitly set it to null that the query param is also visible in the url :)

**Comment by luisfpg** [comment]
That's a point: how do you express null in a query parameter?
https://url/?param= represents an empty string...

Em sex., 27 de out. de 2023 05:06, Tim Quirl ***@***.***>
escreveu:
