### ISSUE TITLE
model index generates bad exports

### ISSUE THREAD

**Issue by GreedyA1** [cyclosproject/ng-openapi-gen#296]
index.ts is missing ./models/ directory in front models exports.

**Comment by mokeev1995** [comment]
This was discussed here: #291 and fixed here: #292 

We're waiting for review & merge this PR.

**Comment by luisfpg** [comment]
Sorry, but I have almost no time for this project nowadays... I'll try to include it this coming week.

**Comment by luisfpg** [comment]
This was fixed in #292

It was previously fixed in `models.ts`, but not in `index.ts`.
