### ISSUE TITLE
From version "0.50.4" models with $ref and nullable: true, are generated without null.

### ISSUE THREAD

**Issue by lubowiecki** [cyclosproject/ng-openapi-gen#301]
Example:

input contract.json
`{
	"openapi": "3.0.3",
	"info": {},
	"servers": [],
	"tags": [],
	"paths": {},
	"components": {
		"schemas": {
			"IsoDateWithTimeDto": {
				"type": "string",
			},
			"Dates": {
				"title": "Dates",
				"type": "object",
				"properties": {
					"activation": {
						"$ref": "#/components/schemas/IsoDateWithTimeDto",
						"nullable": true
					},
				},
			},
			"User": {
				"title": "User",
				"type": "object",
				"properties": {
					"firstname": {
						"type": "string",
						"nullable": true
					},
				},
			}
		}
	}
}
`

it generates:
`import { IsoDateWithTimeDto } from '../models/iso-date-with-time-dto';
export interface Dates {
  activation?: IsoDateWithTimeDto;
}`

and

`export interface User {
  firstname?: string | null; 
}`

While it should be:
`import { IsoDateWithTimeDto } from '../models/iso-date-with-time-dto';
export interface Dates {
  activation?: IsoDateWithTimeDto **| null**;
}`

**Comment by luisfpg** [comment]
This is a limitation of OpenApi: $ref just ignores all sibling properties and is like a 'copy/paste' of the referenced content.
Try the following:

```json
{
"Dates": { 
  "title": "Dates", 
  "type": "object", 
  "properties": { 
    "activation": { 
      "nullable": true,
      "allOf": [
        { "$ref": "#/components/schemas/IsoDateWithTimeDto" }
      ]
    }
  }
}
```
