### ISSUE TITLE
Generate enums as string literal

### ISSUE THREAD

**Issue by detomarco** [cyclosproject/ng-openapi-gen#320]
Version: 0.51.0

#### Schema

```yaml
openapi: 3.0.1
info:
  title: example
  version: 0.0.1
paths:
  /cars:
    get:
      operationId: me
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cars'
          description: OK
components:
  schemas:
    Cars:
      type: object
      properties:
        types:
          type: string
          enum:
            - FERRARI
            - FORD
            - BMW

```

#### Command
```ssh
ng-openapi-gen  --input {input} --output {output}
```

#### Current output

```typescript
export interface Cars {
  types?: 'FERRARI' | 'FORD' | 'BMW';
}
```

#### Desired output
```typescript
export type CarsType = 'FERRARI' | 'FORD' | 'BMW'
export interface Cars {
  types?: CarsType;
}
```

As described above, I'd like to have the option to generate enums as String literals, so I could reuse `CarsType` type in my application code

**Comment by marcschroeder** [comment]
Hey @detomarco, this should already be possible. Try the following example:
`openapi: 3.0.1
info:
  title: example
  version: 0.0.1
paths:
  /cars:
    get:
      operationId: me
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cars'
          description: OK
components:
  schemas:
    Cars:
      type: object
      properties:
        types:
          type: string
          $ref: '#/components/schemas/CarType'
    CarType:
      type: string
      enum:
        - FERRARI
        - FORD
        - BMW
`

Running the command you mentioned should generate a separate file for you that contains an actual typescript enum that you can reuse in your application.

**Comment by detomarco** [comment]
Thanks, that worked indeed.

I'll close this issue!!
