### ISSUE TITLE
Duplicate operationId

### ISSUE THREAD

**Issue by marcschroeder** [cyclosproject/ng-openapi-gen#323]
Currently it is not possible to generate multiple operations using the same operationId.
While this follows the OpenAPI spec - https://swagger.io/specification/ - this prevents different services to have the same method e.g. "list" or "create" even though this might make sense.
To ensure uniqueness a number is added to none-unique operations at the moment.

Would a PR be accepted that adds a new command line parameter to disable this behavior? This would allow to generate easier to read implementations.

**Comment by luisfpg** [comment]
You can try using the `x-operation-name` vendor extension.
Check the project readme.

Em sáb., 1 de jun. de 2024, 10:20, Marc Schröder ***@***.***>
escreveu:

**Comment by marcschroeder** [comment]
I will try that thanks!
