### ISSUE TITLE
Error on API generatio

### ISSUE THREAD

**Issue by Nikotiine** [cyclosproject/ng-openapi-gen#324]
Hello Team, I have a problem with generating models using this API. I only have this problem on Windows 10 (I tried with Ubuntu under WSL, same problem). Do you have any idea how to unlock this for me?

Error on API generation from https://acs-preprod.proxy-preprod.modulr.fr/doc/acs.json: ResolverError: Error downloading https://acs-preprod.proxy-preprod.modulr.fr/doc/acs.json
unable to get local issuer certificate

**Comment by luisfpg** [comment]
I use Linux, and here it works: `ng-openapi-gen --input https://acs-preprod.proxy-preprod.modulr.fr/doc/acs.json` generates correctly.
Sorry, can't help you with Windows. Maybe there are incompatible SSL versions / algorithms?
