### ISSUE TITLE
[feature] add "type" keyword in export/import to prevent re-exportation error with TS IsolatedModules option

### ISSUE THREAD

**Issue by Adrii77** [cyclosproject/ng-openapi-gen#325]
Enable typescript's `isolatedModules` option causes a re-exportation error from `model.ts` generated file.

![Capture d’écran 2024-07-17 à 14 46 38](https://github.com/user-attachments/assets/93e1f8d1-ad1f-48e8-b7c5-0e263094cd15)

Is it possible to add the typescript "type"'s keyword for import and export  ? 

I saw Angular CLI will enable `isolatedModules` option by default for new projects.

I'm using Angular 18.1

**Comment by luisfpg** [comment]
You can just adjust the `modelIndex.handlebars` template.
I'm not sure if this would always be failproof or depends on the model.
Enums by default are generated as classes, but you can set in options `"enumStyle": "alias"` to generate as an union type with string values. In that case it would really be type-only.
So, given the very short time I'm having for this project, I'd recommend editing the template and setting the enumStyle if you need this.
