### ISSUE TITLE
How to Implement Two Different APIs with Separate Root URLs

### ISSUE THREAD

**Issue by Gatos90** [cyclosproject/ng-openapi-gen#327]
Hi everyone,

I'm working on a project where I need to integrate two different APIs, each with its own root URL. Does anyone have suggestions or best practices for handling multiple root URLs ?

Thanks in advance for your help!

Greetings,

**Comment by Leonardonline** [comment]
Hi, in my case, I created 2 npm script that generate 2 different subfolder (api/*) pointing to (supposed) different openApi file  specification.

**Comment by luisfpg** [comment]
Yes, handle both as totally independent generations.
You can set a configuration file per api, each with distinct output dirs.
