### ISSUE TITLE
Duplicate service methods using multiple similar content types

### ISSUE THREAD

**Issue by BaerMitUmlaut** [cyclosproject/ng-openapi-gen#33]
When generating a service for the attached API (which was generated by swagger), some methods are duplicated within the service.

[api.zip](https://github.com/cyclosproject/ng-openapi-gen/files/3447122/api.zip)

**Comment by luisfpg** [comment]
We should handle all JSON `requestBody` variants as a single variant.
For this we'll have to get the first definition.
