### ISSUE TITLE
Blob response should not be typed like a json

### ISSUE THREAD

**Issue by Xample** [cyclosproject/ng-openapi-gen#331]
Hello, unlike json request which should be typed properly, [the "blob" responseType should have a "Blob" resultType.](https://github.com/angular/angular/blob/main/packages/common/http/src/client.ts#L174-L178) 

the [resultType ](https://github.com/cyclosproject/ng-openapi-gen/blob/master/lib/operation-variant.ts#L43)must be "Blob" (PascalCase) if the [responseType](https://github.com/cyclosproject/ng-openapi-gen/blob/master/lib/operation-variant.ts#L44) is a "blob" (lowercase).

I can imagine this possible 2 lines fix:

      this.responseType = this.inferResponseType(successResponse, operation, options);
      this.resultType = this.responseType === "blob" ? "Blob" : successResponse.type;

**Comment by luisfpg** [comment]
Can you share the openapi definition?

**Comment by Xample** [comment]
Hello, I will take a look tomorrow. The Mime type of the content was probably application/* or application/octet-stream.

**Comment by Xample** [comment]
Ok it was « application/json » but I realized I was missing the « format : binary » in the schema part. Using format : binary generates a proper blob object type.
