### ISSUE TITLE
Add support for model namespaces

### ISSUE THREAD

**Issue by snebjorn** [cyclosproject/ng-openapi-gen#39]
According to https://github.com/OAI/OpenAPI-Specification/issues/1362 namespaces are "supported" and tooling should handle them gracefully.

Given this schema with a namespace
```jsonc
{
  "openapi": "3.0.0",
  // omitted
  "components": {
    "schemas": {
      "MY_NAMESPACE.FooBar": {
        // omitted
      }
    }
  }
}
```
Generates this TS model
```ts
export interface MY_NAMESPACE.FooBar  {}
```
`.` is not an allowed character in an interface.

https://github.com/openapitools/openapi-generator-cli handles this by just generating

```ts
export interface MYNAMESPACEFooBar  {}
```

**Comment by snebjorn** [comment]
Perhaps an option to strip the namespace from the generated model could be added along with this fix.

So an option like `excludeNamespaceInModels: boolean`. The default value isn't important as namespaces doesn't currently work, so either will do :)

**Comment by objt-ba** [comment]
imho, the only correct handling, would be to translate namespaces to folders.
so, that would roughly mean:

     |-- MYNAMESPACE
          |-- foobar.interface.ts

with then the code

    export interface FooBar {}

an import would then look as follows:

     import { FooBar } from '... /MYNAMESPACE/foobar.interface.ts'.

and if that ever comes down to a clash, of 2 interfaces having the same name:

    import { FooBar as MyNamespaceFooBar } from '.../MYNAMESPACE/foobar.interface.ts'
    import { FooBar as MyOtherFooBar }           from '.../MYOTHER/foobar.interface.ts'
