### ISSUE TITLE
generated model interfaces are lowercase

### ISSUE THREAD

**Issue by derdeka** [cyclosproject/ng-openapi-gen#41]
I tried this generator on our openapi spec and it works quite well. Thanks.

I just wondering why the generated model interfaces are lowercase (with my openapi spec). I guess there is an encoding of the typeName missing here: https://github.com/cyclosproject/ng-openapi-gen/blob/4c98afe3162190d45db85e93f428f699840081df/lib/model.ts#L34

I fixed that by replacing
`this.typeName = name;`
with
`this.typeName = typeName(name);`

**Comment by toucdi** [comment]
@derdeka interfaces name fix work but the import references is not fixed. Can you check?

**Comment by derdeka** [comment]
My first approach did not work in all cases. I tried something else:
https://github.com/cyclosproject/ng-openapi-gen/blob/4c98afe3162190d45db85e93f428f699840081df/lib/gen-utils.ts#L84

replaced `${baseName}` with `${typeName(baseName)}`
