### ISSUE TITLE
Interfaces class name with first char lowerCase

### ISSUE THREAD

**Issue by toucdi** [cyclosproject/ng-openapi-gen#42]
Hi,

every times i generate from yaml or json, the interfaces generated have the class name lowerCase on first char. 

Example:

> export interface addressFK  {
>   fkIdIndirizzo?: string;
> }
> 

Expected Example: 
> export interface AddressFK  {
>   fkIdIndirizzo?: string;
> }

Can someone help me? Is that a bug?

**Comment by derdeka** [comment]
duplicate of #41 ?

**Comment by toucdi** [comment]
yes i think is same issue. I think the class have do be mandatory with first letter uppercase. How can i use this version? in 0.6.0 i have same issue.
