### ISSUE TITLE
Improve the file generation by generating in a sibling folder and synchronizing changes instead of removing the output folder

### ISSUE THREAD

**Issue by michalsteyn** [cyclosproject/ng-openapi-gen#46]
When running ng-openapi-gen while the project is open in VS Code, I often get file contention issues. 

The error looks something like this:
```
Error on API generation from http://localhost:8081/NameMatcher/NameMatcherService/swagger/v1/swagger.json: Error: EPERM: operation not permitted, mkdir 'D:\ICM\GIT\AirStack\AirApp\src\App\apps\air-app\src\app\ms\subscription\models'
```

If you then open Explorer and try to access the models folder, Explorer will complain that the models folder is not accessible, with an error description of Access Denied.

The only workaround is to close VS Code first and then run ng-openapi-gen.

This issue did not happen with ng-swagger-gen.

What about adding an option to not delete the various sub directories in the auto-generated output directory?

**Comment by luisfpg** [comment]
The current approach is to just remove the whole output directory, which is too aggressive.
I'll change the approach: generating in another temporary directory, then syncing changes to the actual output directory, and finally removing that temporary directory.

**Comment by michalsteyn** [comment]
That sounds perfect! Thanks.
