### ISSUE TITLE
Will --gen-config be available ?

### ISSUE THREAD

**Issue by gilsdav** [cyclosproject/ng-openapi-gen#5]
Will you add `--gen-config` option or must we made a script to do it ?

**Comment by luisfpg** [comment]
It can be added, but is not a priority right now...
The configuration is pretty static...
What is the rationale for needing a script for it?

**Comment by gilsdav** [comment]
Thank's for your answer.
It's used in a project generator. So we use `--gen-config` to generate config files.
If it doesn't existe, we will have to make this generator.

**Comment by luisfpg** [comment]
I'm closing this question, as there are no plans for now to add the --gen-config option (of course, a PR is always welcome).
