### ISSUE TITLE
Doesn't handle a period within a schema name

### ISSUE THREAD

**Issue by Tiberriver256** [cyclosproject/ng-openapi-gen#51]
## Example
![image](https://user-images.githubusercontent.com/6989492/68481139-6b354780-0204-11ea-8872-1adcf0c4c478.png)

## Produces
![image](https://user-images.githubusercontent.com/6989492/68481647-c4ea4180-0205-11ea-8b01-6e69d2d6267a.png)

**Comment by luisfpg** [comment]
This is a duplicate of #39
