### ISSUE TITLE
"false" in path parameter is replaced by an empty string

### ISSUE THREAD

**Issue by MikeKovetsky** [cyclosproject/ng-openapi-gen#53]
Similar to https://github.com/cyclosproject/ng-openapi-gen/issues/48 we shold allow boolean **false** adding to path parameters in RequestBuilder.

**Comment by MikeKovetsky** [comment]
What do you think about removing **|| ''** in https://github.com/cyclosproject/ng-openapi-gen/blob/master/templates/requestBuilder.handlebars#L140 ?

**Comment by luisfpg** [comment]
Definitively a bug.
I've been overloaded with work in the last few weeks, but hopefully things will settle down in the next 2-3 weeks. I'll work to get it done by then.
