### ISSUE TITLE
Error: ENOTEMPTY: directory not empty, rmdir './**/*'

### ISSUE THREAD

**Issue by shorielov-is** [cyclosproject/ng-openapi-gen#56]
I get an error after the successful generation of the API.
`Error on API generation from https://localhost:5002/swagger/v1/swagger.json: Error: ENOTEMPTY: directory not empty, rmdir './src/app/core/api$'`

I think it's because you are using the fs-extra package.

![image](https://user-images.githubusercontent.com/27416149/71515973-fe0e6c00-28ae-11ea-8579-e511e62f6ef2.png)

**Comment by luisfpg** [comment]
Changing to rimraf in version 0.7.1 to fix this.
