### ISSUE TITLE
simple non-nullable boolean being generated as optional

### ISSUE THREAD

**Issue by tommck** [cyclosproject/ng-openapi-gen#59]
I have a simple interface with a non-nullable boolean value but ng-openapi-gen is converting this to an optional field in the output.

input:
```json
      "Foo.Bar.FooInfo": {
        "type": "object",
        "properties": {
          "isTrue": {
            "type": "boolean"
          }
        },
        "additionalProperties": false
      },
```
output:
```ts
interface FooInfo {
   isTrue?: boolean;
}
```

There is nothing optional about `isTrue`. it should not have `?:` on the declaration

**Comment by tommck** [comment]
I'm guessing I'm missing something about the spec, since I'm a newb about this.

So, either the generator of the JSON was incorrect, or this product is incorrect.

oh.... does it have to be labelled as `required` to be considered non-optional?

**Comment by luisfpg** [comment]
Properties are optional by default.
To make them required, do something like:
```json
Foo.Bar.FooInfo": {
        "type": "object",
        "required": ["isTrue"]
        "properties": {
          "isTrue": {
            "type": "boolean"
          }
        },
        "additionalProperties": false
      }
```

**Comment by tommck** [comment]
dammit.. ok, cool.. thanks for the info.  Sorry for the false negative
