### ISSUE TITLE
Why Method Name is Camel Case ?

### ISSUE THREAD

**Issue by MR-MAP** [cyclosproject/ng-openapi-gen#60]
hi,

when my json is :

`
"/Api/Applications/New": {
      "get": {
        "tags": [
          "Applications"
        ],
        "operationId": "GetNew",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ApplicationEditableVMFormlyVMFeedBack"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApplicationEditableVMFormlyVMFeedBack"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApplicationEditableVMFormlyVMFeedBack"
                }
              }
            }
          }
        }
      }
    },
...
`

Generater method name is: getNew$json

how to change method name like ng-swagger : GetNew ?

**Comment by luisfpg** [comment]
That was actually a problem in ng-swagger-gen, as, by convention, methods in TypeScript / Angular should be camel case with first lower.
In ng-openapi-gen that was fixed from the start. There's no way to change it.

**Comment by mpaxglobal** [comment]
Hey @luisfpg, my generated method names are like `apiLoginPost$Json`, `apiUsersPut$Json$Json`, `apiUsersIdGet$Json` etc. How can I get rid of `$...` part? so I get only `apiLoginPost` (even more ideally without `api` prefix)?

Thanks in advance!

**Comment by questionablequestion** [comment]
Hey @luisfpg, my generated method names are like apiLoginPost$Json, apiUsersPut$Json$Json, apiUsersIdGet$Json etc. How can I get rid of $... part? so I get only apiLoginPost (even more ideally without api prefix)?

Thanks in advance!
