### ISSUE TITLE
Unique names SDK

### ISSUE THREAD

**Issue by sangamk** [cyclosproject/ng-openapi-gen#61]
I was wondering why names have to be unique in the generated SDK even though they belong to their own class.

``
Duplicate operation id 'get'. Assuming id get_1 for operation '/employees.get'.
Duplicate operation id 'create'. Assuming id create_1 for operation '/employees.post'.
Duplicate operation id 'getById'. Assuming id getById_1 for operation '/employees/{id}.get
``

Due to this we cannot use generic interfaces as wrappers for the SDK.

**Comment by luisfpg** [comment]
From the [specification](https://swagger.io/specification/#operationObject):

> `operationId`: Unique string used to identify the operation. The id MUST be unique among all operations described in the API. The operationId value is case-sensitive. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is RECOMMENDED to follow common programming naming conventions.

You can, however, use the `x-operation-name` vendor extension. I've added the [supported vendor extensions](https://github.com/cyclosproject/ng-openapi-gen#supported-vendor-extensions) section to the README file.
