### ISSUE TITLE
rootUrl is not defined when writing configuration template

### ISSUE THREAD

**Issue by reppners** [cyclosproject/ng-openapi-gen#65]
`servers` in the open api spec file is not evaluated as per https://swagger.io/docs/specification/api-host-and-base-path/. The handlebars template for the api configuration shows the default configuration `rootUrl` should be populated by the template context variable `rootUrl` but it isn't.

My use case is that the OpenApi `servers` spec contains a single member that has a relative basepath set as url. This should be reflected in the generated code as no manual basepath configuration should be necessary.

If you're accepting PRs on this let me know and I'm happy to contribute!

**Comment by luisfpg** [comment]
Actually, the root URL was never being read from the specification.
Will be fixed in 0.8.0.

**Comment by reppners** [comment]
Awesome! 👍
