### ISSUE TITLE
ModuleWithProviders references need to use an explicit generic type in angular 9

### ISSUE THREAD

**Issue by JeroMiya** [cyclosproject/ng-openapi-gen#69]
In generated services, you'll see references to ModuleWithProvider without an explicit type. This is no longer allowed in angular9:

```TypeScript
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders {
    return {
      ngModule: ApiModule,
// etc....
```

It should use an explicit generic type:

```TypeScript
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
```

Looks like this is fixed in:
https://github.com/cyclosproject/ng-openapi-gen/pull/67

**Comment by luisfpg** [comment]
Yes, @RGunning shared a PR for this.
I'm still in vacation, and will try to test and merge it next week.
