### ISSUE TITLE
No CHANGELOG

### ISSUE THREAD

**Issue by tommck** [cyclosproject/ng-openapi-gen#71]
This is kind of a feature request.

There doesn't seem to be any change log telling us what has changed between versions.
I would be good to know, especially when updating from 0.7.x to 0.8.x, etc.. 

Could you start documenting changes going forward?

**Comment by tommck** [comment]
I did just find the "releases", which gives this information too..

**Comment by luisfpg** [comment]
Yes, they are listed in the page: https://github.com/cyclosproject/ng-openapi-gen/releases
