### ISSUE TITLE
text/json response type should be handled as JSON instead of text

### ISSUE THREAD

**Issue by vadjs** [cyclosproject/ng-openapi-gen#75]
0.7.2 -> 0.8.0
During this update response types of request builders was broken.
The reasiest way to see the bug is [this gist](https://gist.github.com/vadjs/d66c310a13c1466280fd0dfebbd00634). Here are swagger.json file that reproduces bug and broken methods.

Problem is that in new vesrion `RequestBuilder` parameter `responseType` was changed from `json` to `text`.

**Comment by luisfpg** [comment]
Actually, what broke it was that `text/json` is not a valid response type, and is confusing the generator to be plain text.
Will be fixed in 0.8.1.
