### ISSUE TITLE
rootUrl not rendered in configuration because missing in template model 

### ISSUE THREAD

**Issue by reppners** [cyclosproject/ng-openapi-gen#79]
I'm sorry to report that rendering the rootUrl based on the first entry of `servers` does not work.

It seems that the model for rendering the template is not populated with the rootUrl:
https://github.com/cyclosproject/ng-openapi-gen/blob/0d05410561387ed1505a681b0ae681263cc1ccd9/lib/ng-openapi-gen.ts#L74-L80

**Comment by luisfpg** [comment]
Mmm... this line should do it:

https://github.com/cyclosproject/ng-openapi-gen/blob/master/lib/ng-openapi-gen.ts#L122

There's also a test that checks whether the rootUrl is correctly populated:

https://github.com/cyclosproject/ng-openapi-gen/blob/master/test/all-operations.spec.ts#L14

The expected output is that the ApiConfiguration has the rootUrl populated. Isn't this happening?

**Comment by reppners** [comment]
Sorry for the inconvenience, it was a misconfiguration on our side :weary:
