### ISSUE TITLE
Self-referencing object type with dots in Schema name results in build errors

### ISSUE THREAD

**Issue by tommck** [cyclosproject/ng-openapi-gen#86]
I tweaked a simple OpenAPI 3.0 spec (file attached) to rename "Pet" to "One.Two.Pet" and have that object contain a reference to itself:

```yaml
components:
  schemas:
    One.Two.Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
        pets:
          type: array
          items:
            $ref: "#/components/schemas/One.Two.Pet"
```
This results in this TS code (entire file):
```ts
/* tslint:disable */
export interface Pet {
  id: number;
  name: string;
  pets?: Array<OneTwoPet>;
  tag?: string;
}
```
the "OneTwoPet" does not exist.
[pets-with-pets.txt](https://github.com/cyclosproject/ng-openapi-gen/files/4376336/pets-with-pets.txt)

**Comment by tommck** [comment]
Third time I'm filing an issue and it might actually be a real issue this time! ;)

**Comment by tommck** [comment]
If I can get time to do it, I can try to fix this, or at least create a failing unit test

**Comment by luisfpg** [comment]
> Third time I'm filing an issue and it might actually be a real issue this time! ;)

Well, this time it is a bug indeed ;)
Thanks for the PR.
Will merge and tweak if needed.

**Comment by tommck** [comment]
The fix felt a bit awkward, so that's why I put the comment in there about it probably being in the wrong place.

**Comment by tommck** [comment]
@luisfpg This still seems to be a problem... here's another quick sample JSON file:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Blah"
  },
  "paths": {},
  "components": {
    "schemas": {
      "Foo.Bar.Baz": {
        "required": [
          "description",
          "childDetails"
        ],
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "childDetails": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Foo.Bar.Baz"
            }
          }
        },
        "additionalProperties": false
      }
    }
  }
}
```

Output:

```ts
/* tslint:disable */
export interface Baz {
  childDetails: Array<FooBarBaz>;
  description: string;
}
```
:(

**Comment by tommck** [comment]
I'll open another issue
