### ISSUE TITLE
responseType blob causes errors

### ISSUE THREAD

**Issue by murieletrentini** [cyclosproject/ng-openapi-gen#88]
My generated controller.ts all use the responseType 'blob'. This causes problems, since the actual type returned by the api is JSON. Is there a way to configure the response type?

Generated Code:

```
list$Response(params?: { 
}): Observable<StrictHttpResponse<Array<Group>>> {
    const rb = new RequestBuilder(this.rootUrl, GroupControllerService.ListPath, 'get');
    if (params) {
    }
    return this.http.request(rb.build({
      responseType: 'blob',
      accept: '*/*'
    })).pipe(
      filter((r: any) => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<Array<Group>>;
      })
    );
  }
```

produces errors like:
TypeError: groups.map is not a function
because groups is now a blob instead of an array

Changing the response type to json fixes the error:
```
list$Response(params?: {

  }): Observable<StrictHttpResponse<Array<Group>>> {

    const rb = new RequestBuilder(this.rootUrl, GroupControllerService.ListPath, 'get');
    if (params) {
    }
    return this.http.request(rb.build({
      responseType: 'json',
      accept: '*/*'
    })).pipe(
      filter((r: any) => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<Array<Group>>;
      })
    );
  }
```

Seems like this was an issue before? see: #75 
I'm using "ng-openapi-gen": "^0.8.2"

**Comment by luisfpg** [comment]
This is probably because the declared content type in your descriptor isn't `application/json`.
Can you, please, post a snippet of your openapi descriptor for that operation?

**Comment by murieletrentini** [comment]
This is the corresponding part form the openapi.json
```
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
  "openapi": "3.0.1",
  "paths": {
    "/api/v1/groups": {
      "get": {
        "operationId": "list",
        "responses": {
          "200": {
            "description": "default response",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Group"
                  }
                }
              }
            }
          }
        },
        "tags": [
          "group-controller"
        ]
      }
    },
```

**Comment by luisfpg** [comment]
Try changing the `"*/*"` content type to `"application/json"` and it should work.
The problem is that the generator doesn't know it should be a JSON, as it is declared that can be anything.

**Comment by murieletrentini** [comment]
Indeed that helped. Thanks a lot for the fast response!

**Comment by souhaibachour** [comment]
Thanks a lot for your help!

**Comment by The-Lone-Druid** [comment]
This is really embarrassing for those using auto generated API docs of a real product, really have to get into fight with the backend team to resolve the issue 😂
