### ISSUE TITLE
Support properties with invalid characters on identifiers

### ISSUE THREAD

**Issue by FrankiePo** [cyclosproject/ng-openapi-gen#93]
My API is written in kebab-case
The library generates following model:
```ts
/* tslint:disable */
export interface MultiFormAttachmentDto {
  /**
   * The description of the attachment.
   */
  attachment-description?: string;

  /**
   * The name of the attachment.
   */
  attachment-name?: string;
  // ....
}
```
How can I convert all my models to camelCase?

**Comment by luisfpg** [comment]
We cannot change the property names, because that's exactly what is going to be serialized / deserialized to / form JSON.
However, in case the property contains invalid identifier characters, we should declare them as string.
So, I'm adding the bug label and changing the title.
