### ISSUE TITLE
Error on API generation from xxx.json: Error: ENOTEMPTY: directory not empty, rmdir 'xxx/api$'

### ISSUE THREAD

**Issue by spotonlasse** [cyclosproject/ng-openapi-gen#94]
Could not rmdir sibling folder on windows when generating on startup.

rmdir works fine when i try it myself but not from ng-openapi-gen

**Comment by luisfpg** [comment]
I'm sorry, I don't use Windows and have no way to reproduce. Hence, I can't fix it.
A PR is welcome.
