### ISSUE TITLE
Models generated can contains unknowns types

### ISSUE THREAD

**Issue by Erim32** [cyclosproject/ng-openapi-gen#96]
Exemple of generated model:
In the following case, uid and component are not ts valid types of data.
Maybe change unknowns types to "any".

export interface Menu {
  description?: string;
  id: string;
  menusections?: Array<{ 'id': string, 'name': string, 'dishes'?: component, 'menu'?: string }>;
  restaurant?: { 'id': string, 'name': string, 'slug'?: uid, 'price_range'?: string, 'closing_period'?: component, 'contact_email'?: string, 'stars': number, 'averagePrice'?: number, 'address'?: string, 'cover'?: string, 'timestamp'?: timestamp, 'images'?: Array<string>, 'short_description'?: string, 'since'?: string, 'categories'?: string, 'description': string, 'services'?: component, 'menu'?: string, 'opening_times'?: component, 'dz'?: dynamiczone };
}

**Comment by luisfpg** [comment]
Does the OpenAPI 3 spec allows referencing a property of an undeclared type?
If it is not on the spec, it won't be support.
