### ISSUE TITLE
Add a configuration option to not use the $Json suffix

### ISSUE THREAD

**Issue by aersamkull** [cyclosproject/ng-openapi-gen#99]
Hi There,
Great project! I'm using it on a big project and will most likely use it on a lot of projects from now on. Therefore, I have some wishes :) 

Currently, if you only have one Content Type in a Respones, there is no Suffix, while there is a Suffix when having multiple Content Types. I always have Json in the Content Types, but sometimes I have to add a 2nd one to a specific Operation. This will break the generated Code, as I now have to use the Suffix for Json. I'd therefore propose to always generate the Suffix for everything that is now Json and to not generate a Suffix for Json. This makes Json first-class, but looking at the spec of OpenApi, Json is first-class, too. One could of course introduce an option for this behavior.

I'd do a PR if required.

**Comment by luisfpg** [comment]
What you're asking for makes sense.
Of course, a PR is welcome.
Otherwise, will do it when time permits.

**Comment by luisfpg** [comment]
Just to define in case you try a PR: the configuration option could be `skipJsonSuffix`.
You would need to change the `lib/operation.ts` file, in the `variantMethodPart`.
Basically, this line:
```typescript
return `$${typeName(type)}`;
// Replace with
return this.options.skipJsonSuffix && type === 'json' ? '' : `$${typeName(type)}`;
```
Also, don't forget to add the option to `ng-openapi-gen-schema.json`

**Comment by aersamkull** [comment]
As a counterproposal one could make it a bit more generic and call it something like "defaultResponseType" and make it work for other something like a BSON/Yaml/Csv-oriented Api. I personally never had such a use case, but I think this might be useful for someone.

**Comment by luisfpg** [comment]
Well, there could have something like that.
But I prefer to keep it simple for now, because we handle suffixes from content type parts.
So, for example, application/json, text/json and application/my-custom+json are all handled as json.
Perhaps for a full support we'd need a more fine grained mapping, and that's not something I'm personally fond of, because it would make things more complex out of the box.

**Comment by aersamkull** [comment]
Just thought I mention it, but you're right, simplicity is surely more important for now.
